historique_historique:
    resource: "@HistoriqueBundle/Resources/config/routing/historique.yml"
    prefix:   /historique

historique_homepage:
    path:     /
    defaults: { _controller: HistoriqueBundle:Default:index }
